# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: buyback.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rbuyback.proto\x12\rbuyback_proto\x1a\x1cgoogle/protobuf/struct.proto\",\n\x07ReqItem\x12\x0f\n\x07type_id\x18\x01 \x01(\r\x12\x10\n\x08quantity\x18\x02 \x01(\r\"S\n\x06\x42uyReq\x12%\n\x05items\x18\x01 \x03(\x0b\x32\x16.buyback_proto.ReqItem\x12\x10\n\x08language\x18\x02 \x01(\t\x12\x10\n\x08location\x18\x03 \x01(\t\"*\n\x08\x43heckReq\x12\x0c\n\x04hash\x18\x01 \x01(\t\x12\x10\n\x08language\x18\x02 \x01(\t\"\xb3\x01\n\x07RepItem\x12\x0f\n\x07type_id\x18\x01 \x01(\r\x12\x16\n\x0eparent_type_id\x18\x02 \x01(\r\x12\x10\n\x08quantity\x18\x03 \x01(\x01\x12\x0c\n\x04name\x18\x04 \x01(\t\x12\x11\n\tprice_per\x18\x05 \x01(\x01\x12\x13\n\x0b\x64\x65scription\x18\x06 \x01(\t\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x07 \x01(\x08\x12%\n\x04meta\x18\x08 \x01(\x0b\x32\x17.google.protobuf.Struct\"}\n\x03Rep\x12%\n\x05items\x18\x01 \x03(\x0b\x32\x16.buyback_proto.RepItem\x12\x0c\n\x04hash\x18\x02 \x01(\t\x12\x0b\n\x03sum\x18\x03 \x01(\x01\x12\x11\n\ttimestamp\x18\x04 \x01(\x04\x12\x0f\n\x07version\x18\x05 \x01(\t\x12\x10\n\x08location\x18\x06 \x01(\t2q\n\x07\x42uyback\x12\x34\n\x05\x43heck\x12\x17.buyback_proto.CheckReq\x1a\x12.buyback_proto.Rep\x12\x30\n\x03\x42uy\x12\x15.buyback_proto.BuyReq\x1a\x12.buyback_proto.Repb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'buyback_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _REQITEM._serialized_start=62
  _REQITEM._serialized_end=106
  _BUYREQ._serialized_start=108
  _BUYREQ._serialized_end=191
  _CHECKREQ._serialized_start=193
  _CHECKREQ._serialized_end=235
  _REPITEM._serialized_start=238
  _REPITEM._serialized_end=417
  _REP._serialized_start=419
  _REP._serialized_end=544
  _BUYBACK._serialized_start=546
  _BUYBACK._serialized_end=659
# @@protoc_insertion_point(module_scope)
